[production]
address = "0.0.0.0"
port = 8080
workers = 8
keep_alive = 5
log = "normal"
secret_key = "5vJUFdGGccUU8pePAIYYHKwjc8HL/e46o48zYkLJmnk="
limits = { forms = 32768 }

[development]
address = "0.0.0.0"
port = 8081
workers = 8
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
